"""
Database for BeatMind — user accounts and subscriptions.

Two backends, selected by DB_BACKEND (default "sqlite"):
- sqlite: a single file, today's production setup. Safe only with exactly one writer process —
  SQLite's own file locking is not reliable over a network filesystem (EFS/NFS), which is why
  ECS runs this service as a single task with no overlap during deploys.
- postgres: a real server, selected by DB_BACKEND=postgres with DATABASE_URL set. Handles
  concurrent connections from multiple app instances correctly on its own, which is what makes a
  true zero-downtime rolling deploy (two tasks briefly running together) safe.

Everywhere else in the codebase calls conn.execute(sql, params) directly on the connection object,
exactly like sqlite3 allows, and reads rows by name (row["col"]) or by position (row[0]), exactly
like sqlite3.Row. _PGConnection below reproduces both so that code needs no changes. The handful of
places that used SQLite-only syntax (BEGIN IMMEDIATE, PRAGMA, AUTOINCREMENT, datetime('now'),
INSERT OR IGNORE) are called out in their own modules; see MIGRATION.md.
"""

import os
import re
import sqlite3
from contextlib import contextmanager
from datetime import datetime, timedelta, timezone

DB_BACKEND = os.getenv("DB_BACKEND", "sqlite").lower()
DB_PATH = os.getenv("DB_PATH", "beatmind.db")
DATABASE_URL = os.getenv("DATABASE_URL", "")

if DB_BACKEND not in ("sqlite", "postgres"):
    raise ValueError("DB_BACKEND must be 'sqlite' or 'postgres'")


def is_postgres() -> bool:
    return DB_BACKEND == "postgres"


# ---- Dialect helpers: used only in the handful of CREATE TABLE / raw-SQL spots that differ ----

def autoincrement_pk() -> str:
    """An INTEGER PRIMARY KEY that assigns itself, as the first column of a CREATE TABLE."""
    # BY DEFAULT (not ALWAYS): SQLite's AUTOINCREMENT accepts an explicit id if the INSERT gives
    # one, only generating its own when it doesn't. A test fixture relies on exactly that to seed
    # a well-known row (id=1); ALWAYS would reject it without an explicit OVERRIDING SYSTEM VALUE.
    return "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if is_postgres() else "INTEGER PRIMARY KEY AUTOINCREMENT"


def now_sql() -> str:
    """A SQL expression (not a parameter) for the current time, usable as a column DEFAULT or in SET."""
    return "NOW()" if is_postgres() else "datetime('now')"


_PLACEHOLDER_RE = re.compile(r"\?")


def _translate(sql: str) -> str:
    """SQLite's positional '?' -> psycopg2's '%s'. None of this codebase's SQL contains a literal '?'."""
    return _PLACEHOLDER_RE.sub("%s", sql)


class _PGCursor:
    """Adds sqlite3.Row-style dict AND positional access on top of psycopg2's own cursor."""

    def __init__(self, cursor):
        self._cursor = cursor

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()

    @property
    def rowcount(self):
        return self._cursor.rowcount

    def __iter__(self):
        return iter(self._cursor)


class _PGConnection:
    """Enough of sqlite3.Connection's surface for every caller in this codebase to work unchanged:
    conn.execute(sql, params) directly on the connection, returning something with fetchone/fetchall/
    rowcount, and rows that support both row["col"] and row[0]."""

    def __init__(self, raw):
        self._raw = raw

    def execute(self, sql, params=()):
        from psycopg2.extras import DictCursor
        cursor = self._raw.cursor(cursor_factory=DictCursor)
        cursor.execute(_translate(sql), tuple(params))
        return _PGCursor(cursor)

    def commit(self):
        self._raw.commit()

    def rollback(self):
        self._raw.rollback()

    def close(self):
        self._raw.close()


_pg_pool = None


def _get_pg_pool():
    global _pg_pool
    if _pg_pool is None:
        from psycopg2.pool import ThreadedConnectionPool
        if not DATABASE_URL:
            raise RuntimeError("DATABASE_URL env var is required when DB_BACKEND=postgres")
        _pg_pool = ThreadedConnectionPool(minconn=1, maxconn=20, dsn=DATABASE_URL)
    return _pg_pool


def get_conn():
    if is_postgres():
        return _PGConnection(_get_pg_pool().getconn())
    conn = sqlite3.connect(DB_PATH, check_same_thread=False)
    conn.row_factory = sqlite3.Row
    return conn


def _release(conn):
    if is_postgres():
        _get_pg_pool().putconn(conn._raw)
    else:
        conn.close()


@contextmanager
def db():
    conn = get_conn()
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        _release(conn)


def init_db():
    if is_postgres():
        conn = get_conn()
        conn.close()  # psycopg2 needs no startup PRAGMA; durability is the server's job.
    else:
        # Production stores this database on EFS. WAL's shared-memory index is not
        # supported across network filesystems; set journaling only at startup.
        mode = os.getenv("DB_JOURNAL_MODE", "DELETE" if os.getenv("ENV") == "production" else "WAL").upper()
        if mode not in {"DELETE", "WAL"}:
            raise ValueError("DB_JOURNAL_MODE must be DELETE or WAL")
        conn = get_conn()
        try:
            actual = conn.execute(f"PRAGMA journal_mode={mode}").fetchone()[0]
            if actual.upper() != mode:
                raise RuntimeError("Database journal mode could not be configured")
        finally:
            conn.close()
    with db() as conn:
        conn.execute(f"""
            CREATE TABLE IF NOT EXISTS users (
                id {autoincrement_pk()},
                email TEXT UNIQUE NOT NULL,
                password_hash TEXT NOT NULL,
                name TEXT NOT NULL,
                stripe_customer_id TEXT,
                subscription_status TEXT DEFAULT 'inactive',
                subscription_id TEXT,
                trial_ends_at TEXT,
                created_at TEXT DEFAULT ({now_sql()})
            )
        """)
        add_columns(conn, "users", USER_PLAN_COLUMNS)
        conn.execute(f"""
            CREATE TABLE IF NOT EXISTS stripe_events (
                id TEXT PRIMARY KEY,
                type TEXT NOT NULL,
                processed_at TEXT DEFAULT ({now_sql()})
            )""")
        import billing
        import ai_usage
        billing.init(conn)
        ai_usage.init(conn)


# The subscriber's plan, copied from Stripe by the webhook. Rows from before plans existed keep NULLs.
USER_PLAN_COLUMNS = {
    "plan": "TEXT",
    "plan_tier": "TEXT",
    "plan_lookup_key": "TEXT",
    "plan_interval": "TEXT",
    "included_tracks": "INTEGER",
    "included_cloud": "INTEGER",
    "mixmind": "INTEGER",
    "current_period_end": "TEXT",
    "past_due_since": "TEXT",
    "cancel_at": "TEXT",  # When a pending cancellation ends the plan; NULL when it renews.
    "stripe_account": "TEXT",  # "primary" when stripe_customer_id is on the primary Stripe account; NULL = legacy.
}


def _existing_columns(conn, table: str) -> set[str]:
    if is_postgres():
        rows = conn.execute(
            "SELECT column_name AS name FROM information_schema.columns WHERE table_name = %s", (table,)
        ).fetchall()
    else:
        rows = conn.execute(f"PRAGMA table_info({table})")
    return {row["name"] for row in rows}


def add_columns(conn, table: str, columns: dict[str, str]) -> None:
    """Additive, repeatable migration: add each missing nullable column. Never drops or rewrites data."""
    existing = _existing_columns(conn, table)
    for name, kind in columns.items():
        if name in existing:
            continue
        try:
            conn.execute(f"ALTER TABLE {table} ADD COLUMN {name} {kind}")
        except (sqlite3.OperationalError, Exception) as error:
            if "duplicate column" not in str(error).lower() and "already exists" not in str(error).lower():
                raise  # Another task added it first, otherwise a real problem.


def get_user_by_email(email: str) -> dict | None:
    """Exact match first; otherwise the same address in any letter case (people type 'Sylvia@' and 'sylvia@')."""
    with db() as conn:
        row = conn.execute("SELECT * FROM users WHERE email = ?", (email,)).fetchone()
        if row is None:
            row = conn.execute("SELECT * FROM users WHERE lower(email) = lower(?) ORDER BY id", (email,)).fetchone()
        return dict(row) if row else None


def get_users_by_email_any_case(email: str) -> list[dict]:
    """Every account whose email equals this one ignoring case (older sign-ups kept the case they were typed in)."""
    with db() as conn:
        rows = conn.execute("SELECT * FROM users WHERE lower(email) = lower(?) ORDER BY id", (email,)).fetchall()
        return [dict(row) for row in rows]


def get_user_by_id(user_id: int) -> dict | None:
    with db() as conn:
        row = conn.execute("SELECT * FROM users WHERE id = ?", (user_id,)).fetchone()
        return dict(row) if row else None


def create_user(email: str, password_hash: str, name: str, trial_ends_at: str) -> dict:
    with db() as conn:
        row = conn.execute(
            "INSERT INTO users (email, password_hash, name, trial_ends_at) VALUES (?, ?, ?, ?) RETURNING *",
            (email, password_hash, name, trial_ends_at),
        ).fetchone()
        return dict(row)


def update_user_subscription(
    email: str,
    stripe_customer_id: str,
    subscription_status: str,
    subscription_id: str | None = None,
):
    with db() as conn:
        conn.execute(
            """UPDATE users SET stripe_customer_id=?, subscription_status=?, subscription_id=?
               WHERE email=?""",
            (stripe_customer_id, subscription_status, subscription_id, email),
        )


def update_user_password(user_id: int, password_hash: str) -> None:
    with db() as conn:
        conn.execute("UPDATE users SET password_hash=? WHERE id=?", (password_hash, user_id))


PAST_DUE_GRACE_DAYS = 7


def past_due_grace_days() -> int:
    try:
        return max(0, int(os.getenv("BILLING_PAST_DUE_GRACE_DAYS") or PAST_DUE_GRACE_DAYS))
    except ValueError:
        return PAST_DUE_GRACE_DAYS


def parse_utc(value: str | None):
    if not value:
        return None
    try:
        parsed = datetime.fromisoformat(value)
    except ValueError:
        return None
    return parsed if parsed.tzinfo else parsed.replace(tzinfo=timezone.utc)


def _paid_status(user: dict) -> bool:
    """active/trialing: yes. past_due: yes for a grace period after the first failed renewal while Stripe
    retries the card (BILLING_PAST_DUE_GRACE_DAYS, default 7). unpaid, canceled, incomplete: no."""
    status = user.get("subscription_status")
    if status in ("active", "trialing"):
        return True
    if status == "past_due":
        since = parse_utc(user.get("past_due_since"))
        return since is None or datetime.now(timezone.utc) < since + timedelta(days=past_due_grace_days())
    return False


def subscription_access(user: dict) -> bool:
    """BeatMind access from a Stripe subscription. A MixMind-only plan does not include BeatMind."""
    return user.get("plan_tier") != "mixmind" and _paid_status(user)


def mixmind_comp_emails() -> set[str]:
    """Accounts given MixMind without a plan (internal testing, creator comps): MIXMIND_COMP_EMAILS=a@x.com,b@y.com."""
    return {e.strip().lower() for e in os.getenv("MIXMIND_COMP_EMAILS", "").split(",") if e.strip()}


def mixmind_access(user: dict) -> bool:
    """MixMind is included in Studio, MixMind and the combo plans; not in Starter, Pro, legacy plans or the trial."""
    if str(user.get("email", "")).lower() in mixmind_comp_emails():
        return True
    return bool(user.get("mixmind")) and _paid_status(user)


def trial_active(user: dict) -> bool:
    trial = parse_utc(user.get("trial_ends_at"))
    return bool(trial and datetime.now(timezone.utc) < trial)


def is_subscribed(user: dict) -> bool:
    """Return True if user has BeatMind access through a subscription or the app's free trial."""
    return subscription_access(user) or trial_active(user)
