const assert = require('node:assert/strict'), fs = require('node:fs'), Module = require('node:module'), ts = require('typescript');
const file = require('node:path').resolve(__dirname, '../src/lib/background-polling.ts');
const load = () => {
  const mod = new Module(file, module);
  mod._compile(ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText, file);
  return mod.exports;
};
const values = new Map();
global.localStorage = { getItem: k => values.get(k) ?? null, setItem: (k, v) => values.set(k, v) };
global.document = { visibilityState: 'visible' };
const a = load(), b = load(), now = 100000;
assert.equal(a.backgroundPollingAllowed(now), true);
document.visibilityState = 'hidden';
assert.equal(a.backgroundPollingAllowed(now), false);
document.visibilityState = 'visible';
a.observePollingResponse(new Response('', { status: 200 }), now);
assert.equal(a.backgroundPollingAllowed(now), true);
a.observePollingResponse(new Response('', { status: 429 }), now);
assert.equal(a.backgroundPollingAllowed(now + 59000), false);
assert.equal(b.backgroundPollingAllowed(now + 59000), false, 'Cooldown shared between tabs');
assert.equal(b.backgroundPollingAllowed(now + 60000), true);
b.observePollingResponse(new Response('', { status: 429, headers: { 'Retry-After': '120' } }), now + 60000);
assert.equal(a.backgroundPollingAllowed(now + 179999), false);
assert.equal(a.backgroundPollingAllowed(now + 180000), true);
values.clear();
const date = load();
date.observePollingResponse(new Response('', { status: 429, headers: { 'Retry-After': new Date(now + 10000).toUTCString() } }), now);
assert.equal(date.backgroundPollingAllowed(now + 9999), false);
assert.equal(date.backgroundPollingAllowed(now + 10000), true);
values.clear();
global.localStorage = { getItem: () => { throw Error('Storage disabled'); }, setItem: () => { throw Error('Storage disabled'); } };
const privateMode = load();
privateMode.observePollingResponse(new Response('', { status: 429, headers: { 'Retry-After': 'invalid' } }), now);
assert.equal(privateMode.backgroundPollingAllowed(now + 59000), false);
assert.equal(privateMode.backgroundPollingAllowed(now + 60000), true);
console.log('Hidden-tab pause, shared 429 cooldown, Retry-After and disabled-storage fallback passed.');
