const assert = require('node:assert/strict');
const fs = require('node:fs');
const Module = require('node:module');
const ts = require('typescript');
const file = require('node:path').resolve(__dirname, '../src/lib/chat-index.ts');
const compiled = ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS } });
const mod = new Module(file, module);
mod._compile(compiled.outputText, file);
const { restoreChatIndex, unmatchedServerChats } = mod.exports;
const local = [{ id: 'browser-a', title: 'Same title', sessionId: 'a' }];
const server = [{ id: 'a', title: 'Same title' }, { id: 'b', title: 'Same title' }];
assert.deepEqual(unmatchedServerChats(local, server, null), [server[1]]);
assert.deepEqual(unmatchedServerChats([], server, 'a'), [server[1]]);
assert.deepEqual(unmatchedServerChats([], server, null), server);
assert.equal(server.length, 2, 'Filtering must not delete saved history');
const legacy = [{ id: 'old', title: 'Legacy' }];
assert.deepEqual(restoreChatIndex(legacy, () => JSON.stringify({ sessionId: 'a' })), [{ ...legacy[0], sessionId: 'a' }]);
assert.deepEqual(restoreChatIndex(legacy, () => '{'), legacy);
assert.deepEqual(restoreChatIndex(legacy, () => null), legacy);
assert.deepEqual(restoreChatIndex(local, () => { throw Error('Already indexed'); }), local);
console.log('Local/server chat identity deduplication and legacy restoration passed.');
