const assert = require('node:assert/strict');
const fs = require('node:fs');
const Module = require('node:module');
const ts = require('typescript');
const file = require('node:path').resolve(__dirname, '../src/lib/chat-recordings.ts');
const compiled = ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS } });
const mod = new Module(file, module);
mod._compile(compiled.outputText, file);
const { messageRecordingIds } = mod.exports;
const a = 'a'.repeat(32), b = 'b'.repeat(32);
const action = id => ({ tool: 'audition_part', input: { track: 1 }, result: { recording: { id } } });
assert.deepEqual(messageRecordingIds([{}, { toolCalls: [action(a), action(a)] }, { toolCalls: [action(b), action(a)] }]), [[], [a], [b]]);
assert.deepEqual(messageRecordingIds([{ toolCalls: [action('../x'), action('')] }]), [[]]);
assert.deepEqual(messageRecordingIds([{ toolCalls: [{ tool: 'audition_part', input: { track: 1 }, result: { status: 'failed' } }] }]), [[]]);
assert.deepEqual(messageRecordingIds([{ toolCalls: [action(b)] }, { toolCalls: [action(a)] }]), [[b], [a]]);
console.log('Recording ownership tests passed.');
const c = 'c'.repeat(32);
assert.deepEqual(messageRecordingIds([{ toolCalls: [action(a)] }], [{ id: c, supersedes: b }, { id: b, supersedes: a }]), [[a, b, c]]);
assert.deepEqual(messageRecordingIds([{ toolCalls: [action(a)] }, { toolCalls: [action(b)] }], [{ id: b, supersedes: a }]), [[a], [b]]);
assert.deepEqual(messageRecordingIds([{ toolCalls: [action(a)] }], [{ id: b, supersedes: c }]), [[a]]);
assert.deepEqual(messageRecordingIds([], [{ id: a, supersedes: b }, { id: b, supersedes: a }]), []);
