const assert = require('node:assert/strict');
const fs = require('node:fs');
const Module = require('node:module');
const ts = require('typescript');
const file = require('node:path').resolve(__dirname, '../src/lib/music-workflow.ts');
const compiled = ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS } });
const mod = new Module(file, module);
mod._compile(compiled.outputText, file);
const { acceptedSound, claimPreviewAutoplay } = mod.exports;
const seen = new Set();
assert.equal(claimPreviewAutoplay('accepted', 'accepted', false, seen), false);
assert.equal(claimPreviewAutoplay('revised', 'revise', false, seen), false);
assert.equal(claimPreviewAutoplay('old', 'pending', true, seen), false);
assert.equal(claimPreviewAutoplay('new', 'pending', false, seen), true);
assert.equal(claimPreviewAutoplay('new', 'pending', false, seen), false, 'Navigation/remount must not replay a preview');
assert.equal(claimPreviewAutoplay('new', 'accepted', false, seen), false);
const followup = acceptedSound('Kick');
assert.equal(followup.content, 'Kick accepted. What would you like to do next?');
assert.equal(followup.choices.length, 3);
assert.equal(followup.choices[0].message, 'Keep Kick as it is. Which part should we choose next?');
console.log('Accepted sound acknowledgment and once-only pending-preview autoplay passed.');
