const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const Module = require('node:module');
const ts = require('typescript');
const file = path.resolve(__dirname, '../src/lib/reference-listening.ts');
const mod = new Module(file, module);
mod.paths = Module._nodeModulePaths(path.dirname(file));
mod._compile(ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2017 } }).outputText, file);
const { latestListening, requestWasSaved, listeningFinished, excerptRangeError, listeningCoverage } = mod.exports;
const running = { excerpts: [], coverage: { full_coverage: true }, job: { status: 'running', completed: 0, total: 14, intent: 'bass', started_at: '2026-09-27T01:00:00Z' } };
const complete = { ...running, job: { ...running.job, completed: 14, status: 'complete' } };
const old = { ...complete, job: { ...complete.job, started_at: '2026-09-26T01:00:00Z' } };
assert.equal(latestListening(old, running), running, 'Old GET cannot replace accepted POST');
assert.equal(latestListening(running, complete), complete, 'Never downgrade completed request');
assert.equal(latestListening(complete, running), complete);
assert.equal(listeningFinished(running), false, 'Historical coverage does not finish a new intent');
assert.equal(listeningFinished(complete), true);
assert.equal(requestWasSaved(complete, { intent: 'bass', sentAt: Date.parse(running.job.started_at), whole: true }), true);
assert.equal(requestWasSaved(old, { intent: 'bass', sentAt: Date.parse(running.job.started_at), whole: true }), false);
assert.equal(requestWasSaved(complete, { intent: 'different', sentAt: Date.parse(running.job.started_at), whole: true }), false);
assert.equal(requestWasSaved(complete, { intent: 'bass', sentAt: Date.parse(running.job.started_at) + 1000, whole: true, previousJobStartedAt: running.job.started_at }), false, 'A recent earlier request is not confirmation of a new submission');
assert.equal(requestWasSaved({ excerpts: [{ intent: 'bass', created_at: running.job.started_at }] }, { intent: 'bass', sentAt: Date.parse(running.job.started_at), whole: false }), true);
assert.equal(excerptRangeError(0, 6, 6), '');
for (const range of [[0, 20, 6], [-1, 5, 20], [0, 31, 60], [NaN, 10, 60], [0, 4, 60]]) assert.notEqual(excerptRangeError(...range), '');
const interval = (start, end, intent = 'current', layer = 'mix') => ({ start_seconds: start, end_seconds: end, intent, layer, validation: 'checks_passed' });
const audited = listeningCoverage({ excerpts: [interval(0, 10, 'old'), interval(0, 10, 'current', 'bass'), interval(0, 3), interval(2, 4), interval(6, 9), interval(NaN, 10)] }, 10, 'current');
assert.equal(audited.covered, 7); assert.equal(audited.percent, 70); assert.deepEqual(audited.gaps, [[4, 6], [9, 10]]);
assert.equal(listeningCoverage({ excerpts: [interval(0, 5), interval(5.00001, 10)] }, 10, 'current').gaps.length, 0);
console.log('PASS listening request identity, stale-read protection, coverage state and excerpt validation');
