apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: pricing-service
  app.kubernetes.io/component: microservice
  app.kubernetes.io/part-of: dollor-platform
