platform :ios, '15.0'
use_frameworks!

target 'eatfaircustomer' do
  # Google Maps
  pod 'GoogleMaps', '~> 9.0'
  pod 'GooglePlaces', '~> 9.0'

  # Firebase (already using SPM, but keeping for reference)
  # pod 'Firebase/Auth'
  # pod 'Firebase/Firestore'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
