platform :ios, '15.0'
use_frameworks!

target 'eatffairdelivery' do
  # Google Maps
  pod 'GoogleMaps', '~> 9.0'
  pod 'GooglePlaces', '~> 9.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
