#!/bin/bash
# SIMPLE MANUAL SETUP - Follow these steps one by one

echo "════════════════════════════════════════════════════════════"
echo "STEP-BY-STEP MANUAL SETUP"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Copy and paste each command below, ONE AT A TIME:"
echo ""
echo "────────────────────────────────────────────────────────────"
echo "STEP 1: Setup Backend"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "cd backend"
echo "python3 -m venv venv"
echo "source venv/bin/activate"
echo "pip install --upgrade pip"
echo "pip install fastapi==0.104.1 uvicorn[standard]==0.24.0 python-dotenv==1.0.0 sqlalchemy==2.0.23 psycopg2-binary==2.9.9 passlib[bcrypt]==1.7.4 python-jose[cryptography]==3.3.0 python-multipart==0.0.6 pydantic==2.5.0 pydantic-settings==2.1.0"
echo ""
echo "────────────────────────────────────────────────────────────"
echo "STEP 2: Setup Database"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "# Make sure PostgreSQL is running first!"
echo "brew services start postgresql@14"
echo ""
echo "# Create database"
echo "dropdb invoice_db"
echo "createdb invoice_db"
echo ""
echo "# Initialize with sample data"
echo "python init_db.py"
echo ""
echo "────────────────────────────────────────────────────────────"
echo "STEP 3: Start Backend (keep this terminal open)"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "uvicorn main_new:app --reload --port 3000"
echo ""
echo "Wait until you see: 'Application startup complete'"
echo ""
echo "────────────────────────────────────────────────────────────"
echo "STEP 4: Setup Frontend (OPEN NEW TERMINAL)"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "cd /Users/jeet/doordash-p2p/frontend"
echo "npm install"
echo "echo 'VITE_API_URL=http://localhost:3000' > .env"
echo "npm run dev"
echo ""
echo "────────────────────────────────────────────────────────────"
echo "STEP 5: Open Browser"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "http://localhost:5173"
echo ""
echo "Login:"
echo "  Email: admin@invoice.com"
echo "  Password: admin123"
echo ""
echo "════════════════════════════════════════════════════════════"
